import React, { Component } from 'react';
import {blue100} from 'material-ui/styles/colors';
import {DayProgram} from './ProgramComponents'


const saturdayPlan = [
  {hour: '', 'groups': []},
  {hour: '11h00', 'groups':[false,
                            false,
                            {name: 'Pays de Galles - Mad Tom Duo (FR) atelier de danse', duration: 3, kind: 'learn'},
                            false]},
  {hour: '11h30', 'groups':[false,
                            false,
                            true,
                            false]},
  {hour: '12h00', 'groups':[false,
                            false,
                            true,
                            false]},
  {hour: '12h30', 'groups':[false,
                            {name: 'Danses de couple - Pierre Chesneau (BE) & Poke (FR) atelier de danse', duration: 3, kind: 'learn'},
                            false,
                            false]},
  {hour: '13h00', 'groups':[{name: 'InFluEnCeS (BE) concert', duration: 2, kind: 'concert'},
                            true,
                            {name: 'Mad Tom Duo (FR) bal', duration: 3, kind: 'bal'},
                            false]},
  {hour: '13h30', 'groups':[true,
                            true,
                            true,
                            false]},
  {hour: '14h00', 'groups':[false,
                            false,
                            true,
                            {name: 'Théâtre Mabotte (BE) théatre enfants', duration: 1, kind: 'theatre'}]},
  {hour: '14h30', 'groups':[false,
                            {name: 'Poke (FR) bal', duration: 3, kind: 'bal'},
                            false,
                            {name: 'Podium libre', duration: 2, kind: 'free'}]},
  {hour: '15h00', 'groups':[false,
                            true,
                            false,
                            true]},
  {hour: '15h30', 'groups':[false,
                            true,
                            false,
                            {name: 'Théâtre Mabotte (BE) théatre enfants', duration: 1, kind: 'theatre'}]},
  {hour: '16h00', 'groups':[{name: 'Initiation bal folk - Carine de Lauw (BE) atelier de danse', duration: 3, kind: 'learn'},
                            false,
                            {name: 'Durif - Champeval (FR) bal', duration: 4, kind: 'bal'},
                            false]},
  {hour: '16h30', 'groups':[true,
                            false,
                            true,
                            {name: 'Théâtre Mabotte (BE) théatre enfants', duration: 1, kind: 'theatre'}]},
  {hour: '17h00', 'groups':[true,
                            false,
                            true,
                            false]},
  {hour: '17h30', 'groups':[false,
                            false,
                            true,
                            {name: 'Théâtre Mabotte (BE) théatre enfants', duration: 1, kind: 'theatre'}]},
  {hour: '18h00', 'groups':[false,
                            {name: 'Duo TTC (FR) bal', duration: 4, kind: 'bal'},
                            false,
                            {name: 'Podium libre', duration: 2, kind: 'free'}]},
  {hour: '18h30', 'groups':[false,
                            true,
                            false,
                            true]},
  {hour: '19h00', 'groups':[{name: 'Elles s\'y promènent (BE) concert', duration: 3, kind: 'concert'},
                            true,
                            false,
                            false]},
  {hour: '19h30', 'groups':[true,
                            true,
                            false,
                            false]},
  {hour: '20h00', 'groups':[true,
                            false,
                            {name: 'Carte blanche à Michel Jacqmain (BE) bal', duration: 4, kind: 'bal'},
                            false]},
  {hour: '20h30', 'groups':[false,
                            false,
                            true,
                            {name: 'Podium libre', duration: 2, kind: 'free'}]},
  {hour: '21h00', 'groups':[false,
                            false,
                            true,
                            true]},
  {hour: '21h30', 'groups':[false,
                            false,
                            true,
                            false]},
  {hour: '22h00', 'groups':[{name: 'Väsen (SE) concert', duration: 3, kind: 'concert'},
                            {name: 'Beat Bouet Trio (FR) bal', duration: 4, kind: 'bal'},
                            false,
                            false]},
  {hour: '22h30', 'groups':[true,
                            true,
                            false,
                            false]},
  {hour: '23h00', 'groups':[true,
                            true,
                            false,
                            false]},
  {hour: '23h30', 'groups':[false,
                            true,
                            false,
                            false]},
  {hour: '00h00', 'groups':[false,
                            false,
                            {name: 'Shillelagh (FR) bal', duration: 4, kind: 'bal'},
                            false]},
  {hour: '00h30', 'groups':[false,
                            false,
                            true,
                            false]},
  {hour: '01h00', 'groups':[false,
                            false,
                            true,
                            false]},
  {hour: '01h30', 'groups':[false,
                            false,
                            true,
                            false]},
  {hour: '02h00', 'groups':[false,
                            false,
                            false,
                            false]},
];


export default class SaturdayProgram extends React.Component {
  render() {
    return (
      <DayProgram plan={saturdayPlan} lang={this.props.lang} />
    );
  }
}
